# Generated by Django 4.2.25 on 2025-10-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('equipe', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='usuarios.torneio')),
            ],
        ),
    ]
